### ISSUE TITLE
Error: can't find '__main__' module

### ISSUE THREAD

**Issue by coopw1** [Kocarus/Manga-Translator-TesseractOCR#3]
I'm trying to run the program with the example images, and I'm getting 

> C:\Users\[User]\AppData\Local\Temp\manga_translate.py\venv\Scripts\python.exe: can't find '__main__' module in 'C:/Users/[User]/AppData/Local/Temp/manga_translate.py'
> 
> Process finished with exit code 1

**Comment by Kocarus** [comment]
There's still "main" function in "manga_translate.py". 
Seem you have to recheck for mispell or something, it's weird that it's detected missing. GL 🤝
